create table bank_account (identification_number varchar(255) not null, balance numeric(19, 2), currency varchar(255), holder_user_id int8, account_type varchar(255), primary key (identification_number));
create table bank_card (identification_number varchar(255) not null, balance numeric(19, 2), currency varchar(255), holder_user_id int8, cvv_or_cvc_code varchar(255), validity_period varchar(255), primary key (identification_number));
create table client (user_id int8 generated by default as identity, name varchar(255), password varchar(255), surname varchar(255), username varchar(255), primary key (user_id));
create table client_roles (clients_user_id int8 not null, roles_id int8 not null);
create table remittance (id int8 generated by default as identity, remittance_currency varchar(255), remittance_type int4, sum numeric(19, 2), user_from varchar(255), user_to varchar(255), primary key (id));
create table role (id int8 generated by default as identity, name varchar(255), primary key (id));
alter table if exists bank_account add constraint FK_33ixo1p3kb42evb885aniwl9b foreign key (holder_user_id) references client;
alter table if exists bank_card add constraint FK_5rw5kypfdx2cfnh0sguux3rfq foreign key (holder_user_id) references client;
alter table if exists client_roles add constraint FKsgkujj8649e59exwr5rlu1p0 foreign key (roles_id) references role;
alter table if exists client_roles add constraint FKjom6rjgtqdg3m6gx44x61dpf3 foreign key (clients_user_id) references client;
insert into role (name) values ('ROLE_USER');
insert into client (name, password, surname, username) VALUES ('алексей',
                                                               '$2y$10$nxuWneE/0CKrRiEkkE9LyOL/IMu.nzIyO4313Uykzp8tZ5EnnxCYK',
                                                               'кострыгин', 'tripeDouble');
insert into client (name, password, surname, username) VALUES ('егор',
                                                               '$2y$10$nxuWneE/0CKrRiEkkE9LyOL/IMu.nzIyO4313Uykzp8tZ5EnnxCYK',
                                                               'иванов', 'doubleDouble');
insert into client (name, password, surname, username) VALUES ('илья',
                                                               '$2y$10$nxuWneE/0CKrRiEkkE9LyOL/IMu.nzIyO4313Uykzp8tZ5EnnxCYK',
                                                               'жданов', 'ilya19');
insert into client_roles (clients_user_id, roles_id) VALUES (1, 1);
insert into client_roles (clients_user_id, roles_id) VALUES (2, 1);
insert into client_roles (clients_user_id, roles_id) VALUES (3, 1);
insert into bank_card (identification_number, balance, currency, holder_user_id, cvv_or_cvc_code, validity_period)
VALUES ('0000000000000000', 1000, 'RUB', 1, '123', '08/24');
insert into bank_card (identification_number, balance, currency, holder_user_id, cvv_or_cvc_code, validity_period)
VALUES ('0000000000000001', 1000, 'RUB', 2, '123', '08/24');
insert into bank_card (identification_number, balance, currency, holder_user_id, cvv_or_cvc_code, validity_period)
VALUES ('0000000000000002', 1000, 'USD', 3, '123', '08/24');
insert into bank_account (identification_number, balance, currency, holder_user_id, account_type)
values ('00000000000000000000', 2000, 'RUB', 1, 'расчетный');
insert into bank_account (identification_number, balance, currency, holder_user_id, account_type)
values ('00000000000000000001', 2000, 'RUB', 2, 'расчетный');
insert into bank_account (identification_number, balance, currency, holder_user_id, account_type)
values ('00000000000000000002', 2000, 'USD', 3, 'расчетный');